// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-sellers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/data.ts
var sellers = [
  { username: "adunni", name: "Cheinly Atelier \u2014 Adunni Okoye", bio: "Handcrafted Nigerian fashion. Ships nationwide via Cheinly Escrow.", type: "seller" },
  { username: "globalsneakers", name: "Global Sneakers Ltd.", bio: "Authentic kicks, fast delivery, escrow-protected.", type: "supplier" }
];
var products = [
  { id: "PRD_83921", name: "Premium Men's Sneakers \u2014 Phantom Black", price: 45e3, description: "Cushioned sole, breathable mesh, size 40\u201345.", sellerUsername: "globalsneakers", inStock: true },
  { id: "PRD_83922", name: "AirFlex Trainers \u2014 Cloud White", price: 52e3, description: "Lightweight streetwear trainers with reinforced heel support.", sellerUsername: "globalsneakers", inStock: true },
  { id: "PRD_83923", name: "Classic Court Sneakers \u2014 Forest Green", price: 39e3, description: "Low-profile court sneakers with a premium suede finish.", sellerUsername: "globalsneakers", inStock: true },
  { id: "PRD_83924", name: "Runner Pro Knit \u2014 Midnight Navy", price: 61e3, description: "Breathable knit runners for daily wear and commuting.", sellerUsername: "globalsneakers", inStock: true },
  { id: "PRD_83925", name: "Retro High Tops \u2014 Sandstone", price: 57500, description: "Padded high tops with durable canvas panels and gum sole.", sellerUsername: "globalsneakers", inStock: false },
  { id: "PRD_83926", name: "Slip-On Loafers \u2014 Onyx", price: 48e3, description: "Smart casual slip-ons with cushioned insoles and grip outsole.", sellerUsername: "globalsneakers", inStock: true },
  { id: "PRD_83927", name: "TrailGrip Sneakers \u2014 Clay Orange", price: 68e3, description: "All-terrain sneakers with textured outsole and waterproof trim.", sellerUsername: "globalsneakers", inStock: true },
  { id: "PRD_77104", name: "Velvet Wrap Dress \u2014 Emerald", price: 42500, description: "Hand-finished velvet wrap dress. Sizes XS\u2013XL.", sellerUsername: "adunni", inStock: true },
  { id: "PRD_77105", name: "Linen Agbada Set \u2014 Cream", price: 86e3, description: "Tailored 3-piece linen agbada set.", sellerUsername: "adunni", inStock: true },
  { id: "PRD_77106", name: "Silk Bubu Dress \u2014 Champagne", price: 53500, description: "Flowing silk bubu with embroidered neckline and side pockets.", sellerUsername: "adunni", inStock: true },
  { id: "PRD_77107", name: "Ankara Co-ord Set \u2014 Sunrise", price: 38e3, description: "Two-piece Ankara set with relaxed trousers and crop jacket.", sellerUsername: "adunni", inStock: true },
  { id: "PRD_77108", name: "Beaded Clutch \u2014 Gold Noir", price: 24500, description: "Evening clutch with hand-beaded finish and chain strap.", sellerUsername: "adunni", inStock: false },
  { id: "PRD_77109", name: "Adire Kimono \u2014 Indigo Wave", price: 47e3, description: "Hand-dyed adire kimono for casual and occasion wear.", sellerUsername: "adunni", inStock: true }
];

// src/lib/mcp/tools/list-sellers.ts
var list_sellers_default = defineTool({
  name: "list_sellers",
  title: "List sellers",
  description: "List every seller and supplier storefront available on Cheinly, including their bio-link username and business type.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(sellers, null, 2) }],
    structuredContent: { sellers }
  })
});

// src/lib/mcp/tools/list-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.0";
var list_products_default = defineTool2({
  name: "list_products",
  title: "List products",
  description: "List active Cheinly products. Optionally filter by seller username, in-stock only, or a text query on name/description.",
  inputSchema: {
    sellerUsername: z.string().trim().min(1).optional().describe("Seller/supplier username (e.g. 'adunni' or 'globalsneakers')."),
    inStockOnly: z.boolean().optional().describe("If true, only return products currently in stock."),
    query: z.string().trim().min(1).optional().describe("Case-insensitive substring to match against name and description."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of products to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ sellerUsername, inStockOnly, query, limit }) => {
    if (sellerUsername && !sellers.some((s) => s.username.toLowerCase() === sellerUsername.toLowerCase())) {
      return { content: [{ type: "text", text: `Unknown seller username: ${sellerUsername}` }], isError: true };
    }
    const q = query?.toLowerCase();
    const results = products.filter((p) => sellerUsername ? p.sellerUsername.toLowerCase() === sellerUsername.toLowerCase() : true).filter((p) => inStockOnly ? p.inStock : true).filter((p) => q ? p.name.toLowerCase().includes(q) || p.description.toLowerCase().includes(q) : true).slice(0, limit ?? 20);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, products: results }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.0";
var get_product_default = defineTool3({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single Cheinly product by its product ID (e.g. 'PRD_83921').",
  inputSchema: {
    productId: z2.string().trim().min(1).describe("Product ID such as 'PRD_83921'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ productId }) => {
    const product = products.find((p) => p.id.toLowerCase() === productId.toLowerCase());
    if (!product) {
      return { content: [{ type: "text", text: `Product not found: ${productId}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cheinly-mcp",
  title: "Cheinly MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the Cheinly marketplace. Use `list_sellers` to see storefronts, `list_products` to browse or search the catalog (optionally filtered by seller), and `get_product` for details on a specific product ID.",
  tools: [list_sellers_default, list_products_default, get_product_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
